name: xianxuan_sae
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.1.31=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_1
  - debugpy=1.8.11=py310h6a678d5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.34.0=pyh907856f_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.0.16=h5eee18b_0
  - packaging=24.2=pyhd8ed1ab_2
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.0=py310h06a4308_0
  - platformdirs=4.3.7=pyh29332c3_0
  - prompt-toolkit=3.0.50=pyha770c72_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - python=3.10.16=he870216_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.10=2_cp310
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py310h06a4308_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h39e8969_0
  - tornado=6.1=py310h5764c6d_3
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.13.0=pyh29332c3_1
  - tzdata=2025a=h04d1e81_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==1.5.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - attrs==25.3.0
      - automated-interpretability==0.0.8
      - babe==0.0.7
      - beartype==0.14.1
      - better-abc==0.0.3
      - blobfile==2.1.1
      - boostedblob==0.15.6
      - certifi==2025.1.31
      - click==8.1.8
      - config2py==0.1.37
      - contourpy==1.3.1
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - dol==0.3.16
      - einops==0.8.1
      - fancy-einsum==0.0.3
      - filelock==3.18.0
      - fonttools==4.56.0
      - gprof2dot==2024.6.6
      - graze==0.1.29
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.27.2
      - huggingface-hub==0.30.2
      - i2==0.1.46
      - idna==3.10
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - jaxtyping==0.3.0
      - jinja2==3.1.6
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - llvmlite==0.44.0
      - lxml==4.9.4
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - nltk==3.9.1
      - numba==0.61.2
      - numpy==1.26.4
      - orjson==3.10.16
      - patsy==1.0.1
      - pillow==11.1.0
      - plotly==5.24.1
      - plotly-express==0.4.1
      - pluggy==1.5.0
      - protobuf==5.29.4
      - psutil==7.0.0
      - py2store==0.1.20
      - pycryptodomex==3.22.0
      - pydantic==2.11.1
      - pydantic-core==2.33.0
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - pytest==8.3.5
      - pytest-profiling==1.8.1
      - python-dotenv==1.1.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.0.0
      - rich==14.0.0
      - sae-lens==5.6.1
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - sentry-sdk==2.24.1
      - setproctitle==1.3.5
      - shellingham==1.5.4
      - simple-parsing==0.1.7
      - sniffio==1.3.1
      - statsmodels==0.14.4
      - tenacity==9.0.0
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - transformer-lens==2.15.0
      - transformers==4.51.3
      - transformers-stream-generator==0.0.5
      - typeguard==4.4.2
      - typer==0.12.5
      - typing-inspection==0.4.0
      - umap==0.1.1
      - umap-learn==0.5.7
      - urllib3==2.3.0
      - uvloop==0.21.0
      - wadler-lindig==0.1.4
      - wandb==0.19.8
      - zstandard==0.22.0
prefix: /home/user/anaconda3/envs/xianxuan_sae
